### ISSUE TITLE
CI: Move Java setup to CI-worker

### ISSUE THREAD

**Issue by wojtas000** [OpenCS-ontology/OpenCS#15]
"Download robot.jar" and "Java installation" steps should be removed from pre-release.yml pipeline and moved to CI-worker's Dockerfile. 
![image](https://user-images.githubusercontent.com/56300703/213879733-0165846a-785b-49ca-8087-d847f2b8a7c3.png)

**Comment by Ostrzyciel** [comment]
The ROBOT part was resolved in: https://github.com/OpenCS-ontology/ci-worker/pull/10

Now we only need to move Java installation to the worker's Dockerfile.
